language: node_js

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: visualiza.tideapps.com
  skip_cleanup: true
  local_dir: dist
  upload-dir: tests3
