language: node_js
node_js:
- '6.10'

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm i

script:
  - ng build --prod

after_success:
  - deploy:
      provider: s3
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      bucket: visualiza.tideapps.com
      skip_cleanup: true
      local_dir: dist
      upload-dir: test

notifications:
  email:
    on_failure: change
    on_success: change