language: node_js
node_js:
- '6.10'

cache:
  directories:
    - node_modules

branches:
  only:
    - release
    - development

before_script:
  - npm install -g @angular/cli
  - npm i

script:
  - if [ "$TRAVIS_BRANCH" = "release" ]; then ng build --prod --base-href /matriculaMedia/; fi
  - if [ "$TRAVIS_BRANCH" = "development" ]; then ng build --prod --base-href /devMatriculaMedia/; fi

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: visualiza.tideapps.com
    skip_cleanup: true
    upload-dir: matriculaMedia
    local_dir: dist
    on:
      branch: release
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: visualiza.tideapps.com
    skip_cleanup: true
    upload-dir: devMatriculaMedia
    local_dir: dist
    on:
      branch: development


notifications:
  email:
    on_failure: change
    on_success: change