language: node_js
node_js:
- '6.10'

cache:
  directories:
    - node_modules

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: visualiza.tideapps.com
  skip_cleanup: true
  local_dir: dist
  upload-dir: test
